name: PHPStan

on:
  push:
    paths:
      - '**.php'
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  static-analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none

      - name: Install dependencies
        run: composer install

      - name: Run PHPStan
        run: vendor/bin/phpstan